#:schema node_modules/wrangler/config-schema.json

[[d1_databases]]
binding = "DB"
database_name = "dev-rtainjapan-app"
database_id = "ce315ce5-bd16-42a5-ae07-52ad7ab2754a"

[[d1_databases]]
binding = "DB"
database_name = "prod-rtainjapan-app"
database_id = "23e5867e-fa8f-4f0e-8492-a08328e903d1"
