// Generated by Wrangler on Thu Jun 27 2024 06:23:44 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	NODE_VERSION: "20.14.0";
	PNPM_VERSION: "9.4.0";
	LOCAL: string;
	SESSION_COOKIE_SECRET: string;
	DB: D1Database;
}
