#:schema node_modules/wrangler/config-schema.json

name = "rtainjapan-admin"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-06-26"

[vars]
NODE_VERSION = "20.14.0"
PNPM_VERSION = "9.4.0"

[env.production.vars]
NODE_VERSION = "20.14.0"
PNPM_VERSION = "9.4.0"

[[d1_databases]]
binding = "DB"
database_name = "dev-rtainjapan-app"
database_id = "0de680aa-7b5c-483e-b0ec-df058e9f866e"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "837a5fe00e454effb28fdfa3f79d450e"

[[env.production.d1_databases]]
binding = "DB"
database_name = "prod-rtainjapan-app"
database_id = "80784fc1-2408-4f77-ace9-238a949c1a7f"

[[env.production.kv_namespaces]]
binding = "SESSION_KV"
id = "b21b848ec91a4a8580e097764bab8420"
