// Generated by Wrangler on Fri Jun 28 2024 06:43:55 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	SESSION_KV: KVNamespace;
	NODE_VERSION: "20.14.0";
	PNPM_VERSION: "9.4.0";
	SUPER_ADMIN_DISCORD_ID: "159600065017675778";
	SESSION_COOKIE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DB: D1Database;
}
