// Generated by Wrangler on Tue Jun 25 2024 02:55:42 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	NODE_VERSION: "20.14.0";
	PNPM_VERSION: "9.4.0";
	DB: D1Database;
}
