// Generated by Wrangler on Wed Jun 26 2024 21:45:18 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	SESSION_KV: KVNamespace;
	NODE_VERSION: "20.14.0";
	PNPM_VERSION: "9.4.0";
	LOCAL: string;
	SESSION_COOKIE_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DB: D1Database;
}
