#:schema node_modules/wrangler/config-schema.json

name = 'rtainjapan-web'
pages_build_output_dir = "./build/client"
compatibility_date = "2024-06-24"

[vars]
NODE_VERSION = "20.14.0"
PNPM_VERSION = "9.4.0"
