[[d1_databases]]
binding = "DB"
database_name = "dev-rtainjapan-app"
database_id = "0de680aa-7b5c-483e-b0ec-df058e9f866e"
migrations_dir = "../db-schema/migrations"

[[d1_databases]]
binding = "DB"
database_name = "prod-rtainjapan-app"
database_id = "4f2a1fca-bb23-4844-bfb2-b1dec2b18a8b"
