#:schema node_modules/wrangler/config-schema.json

[[d1_databases]]
binding = "DB"
database_name = "dev-rtainjapan-app"
database_id = "0de680aa-7b5c-483e-b0ec-df058e9f866e"

[[d1_databases]]
binding = "DB"
database_name = "prod-rtainjapan-app"
database_id = "80784fc1-2408-4f77-ace9-238a949c1a7f"
